apiVersion: v1
kind: Secret
metadata:
  name: workspace-secrets
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "password"
  MONGODB_USER: "user"
  MONGODB_PASSWORD: "password"
  GOOGLE_KEY: "PLACE_HOLDER_VALUE"