apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-database-deployment
  
spec:
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
        - name: database-service
          image: database-service-image
          ports:
            - containerPort: 9095
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
          env:
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: workspace-dev-env
                  key: GRPC_PORT
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: conn-string
                  key: connectionString.standardSrv
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: workspace-dev-env
                  key: MONGO_DATABASE
            - name: QUARKUS_MONGODB_CREDENTIALS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: conn-string
                  key: username
              value:
            - name: QUARKUS_MONGODB_CREDENTIALS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conn-string
                  key: password
            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: workspace-dev-env
                  key: LOGGER_LEVEL
            - name: QUARKUS_MONGODB_CREDENTIALS_AUTH-MECHANISM
              value: "SCRAM-SHA-256"
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "1Gi"
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
            - name: secrets
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: workspace-dev-env
        - name: secrets
          secret:
            secretName: workspace-secrets