apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafkatopic-reader
  namespace: default
rules:
  - apiGroups: ["kafka.strimzi.io"]
    resources: ["kafkatopics"]
    verbs: ["get", "list", "watch"]