apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-backup
  
spec:
  selector:
    matchLabels:
      app: workspace-backup
  template:
    metadata:
      labels:
        app: workspace-backup
    spec:
      containers:
        - name: backup
          image: workspace-backup-image
          ports:
            - containerPort: 9523