apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: database-service-service-hpa
  namespace: tripmonkey-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Service
    name: database-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80