apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-panel
  namespace: tripmonkey-dev
spec:
  selector:
    matchLabels:
      app: admin-panel
  template:
    metadata:
      labels:
        app: admin-panel
    spec:
      containers:
        - name: webapp
          image: admin_panel
          ports:
            - containerPort: 47314
