apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-mongo-express
  namespace: tripmonkey-dev
spec:
    spec:
      containers:
        - name: webapp
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                secretKeyRef:
                  name: conn-string
                  key: connectionString.standardSrv
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: workspace-dev-env
                  key: MONGO_DATABASE
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: conn-string
                  key: username
              value:
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conn-string
                  key: password
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: workspace-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
              value:
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: workspace-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
            - name: secrets
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: workspace-dev-env
        - name: secrets
          secret:
            secretName: workspace-secrets
