apiVersion: v1
kind: Service
metadata:
  name: workspace-database-service
spec:
  type: ClusterIP
  selector:
    app: database-service
  ports:
    - name: grpc
      port: 9095
      targetPort: 9095