apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-mongo-express
spec:
  selector:
    matchLabels:
      app: debug-mongo-express
  template:
    metadata:
      labels:
        app: debug-mongo-express
    spec:
      serviceAccountName: secret-peeker

      initContainers:
        - name: wait-for-secrets-and-pod
          image: curlimages/curl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for conn-string and high-conn-string secrets..."
              
              until curl -sf -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
                --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
                https://kubernetes.default.svc/api/v1/namespaces/default/secrets/conn-string; do
                echo "Waiting for conn-string..."
                sleep 2
              done
              
              until curl -sf -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
                --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
                https://kubernetes.default.svc/api/v1/namespaces/default/secrets/high-conn-string; do
                echo "Waiting for high-conn-string..."
                sleep 2
              done
              
              echo "Secrets are ready. Proceeding..."


      containers:
        - name: debug-mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: high-conn-string
                  key: connectionString.standard
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: workspace-dev-env
                  key: MONGO_DATABASE
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: conn-string
                  key: username
              value:
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conn-string
                  key: password
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: high-conn-string
                  key: username
              value:
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: high-conn-string
                  key: password
            - name: ME_CONFIG_BASICAUTH
              value: "false"
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
            - name: secrets
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: workspace-dev-env
        - name: secrets
          secret:
            secretName: workspace-secrets
