apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: secret-peeker # or your pod's SA
roleRef:
  kind: Role
  name: read-secrets
  apiGroup: rbac.authorization.k8s.io