apiVersion: v1
kind: Secret
metadata:
  name: workspace-secrets
  namespace: tripmonkey-dev
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "password"
  MONGODB_USER: "user"
  MONGODB_PASSWORD: "password"
  GOOGLE_KEY: "TH151SN0TAN4P1P4SSK3Y"