apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tripmonkey-secrets
                  key: mongo_root
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tripmonkey-secrets
                  key: mongo_root_password
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: tripmonkey-secrets
                  key: mongo_user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tripmonkey-secrets
                  key: mongo_user_password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
  selector:
    app: mongodb