apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry-service
spec:
  serviceName: registry-service
  replicas: 1
  selector:
    matchLabels:
      app: registry-service
  template:
    metadata:
      labels:
        app: registry-service
    spec:
      containers:
        - name: registry-service
          image: confluentinc/cp-schema-registry
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://localhost:8081"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: workspace-env
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "localhost"
      volumes:
        - name: config
          configMap:
            name: workspace-env
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    app: registry-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
  selector:
    app: registry-service