apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
spec:
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
        - name: database-service
          image: sprugit/database-service
          ports:
            - containerPort: 9095
          env:
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: workspace-env
                  key: GRPC_PORT
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: workspace-env
                  key: MONGO_HOST
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: workspace-env
                  key: MONGO_DATABASE
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: workspace-secrets
                  key: MONGODB_USER
              value:
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: workspace-secrets
                  key: MONGODB_PASSWORD
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "2Gi"
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
            - name: secrets
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: workspace-env
        - name: secrets
          secret:
            secretName: workspace-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: ClusterIP
  selector:
    app: database-service
  ports:
    - name: grpc
      port: 9095
      targetPort: 9095
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: database-service-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Service
    name: database-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80