apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-service
spec:
  selector:
    matchLabels:
      app: workspace-service
  template:
    metadata:
      labels:
         app: workspace-service
    spec:
      containers:
        - name: webapp
          image: sprugit/workspace-service
          ports:
            - containerPort: 9095
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: workspace-env
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: workspace-env
                  key: GRPC_PORT
            - name: PATCH_PERSIST_HOST
              valueFrom:
                configMapKeyRef:
                  name: workspace-env
                  key: DB_HOST
            - name: WORKSPACE_FETCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: workspace-env
                  key: DB_HOST
            - name: GOOGLE_KEY
              valueFrom:
                secretKeyRef:
                  name: tripmonkey-secrets
                  key: GOOGLE_KEY
            - name: KAFKA_NOTIFICATIONS_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: workspace-env
                  key: KAFKA_NOTIFICATIONS_TOPIC
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "2Gi"
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
            - name: secrets
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
        - name: secrets
          secret:
            secretName: tripmonkey-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-service
spec:
  type: ClusterIP
  selector:
    app: workspace-service
  ports:
    - name: grpc
      port: 9095
      targetPort: 9095