apiVersion: v1
kind: Service
metadata:
  name: workspace-notifications-service
  namespace: tripmonkey-dev
spec:
  type: ClusterIP
  selector:
    app: notifications-service
  ports:
    - name: notifications-port
      port: 8080
      targetPort: 8080