apiVersion: v1
kind: Service
metadata:
  name: workspace-core-service
  namespace: tripmonkey-dev
spec:
  type: ClusterIP
  selector:
    app: workspace-service
  ports:
    - name: grpc
      port: 9095
      targetPort: 9095