apiVersion: v1
kind: Service
metadata:
  name: workspace-rest-service
  namespace: tripmonkey-dev
spec:
  type: ClusterIP
  selector:
    app: workspace-rest-interface
  ports:
    - name: rest-port
      port: 8080
      targetPort: 8080